"""app db

Revision ID: 2ad89dfeea6b
Revises: 
Create Date: 2020-05-28 08:47:08.026062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad89dfeea6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_position'), 'user', ['position'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('in_timestamp', sa.Date(), nullable=True),
    sa.Column('out_timestamp', sa.Date(), nullable=True),
    sa.Column('serial_number', sa.String(length=20), nullable=True),
    sa.Column('product_number', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('length', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('in_filename_record_of_transfer', sa.String(length=100), nullable=True),
    sa.Column('in_url_record_of_transfer', sa.String(length=100), nullable=True),
    sa.Column('out_filename_record_of_transfer', sa.String(length=100), nullable=True),
    sa.Column('out_url_record_of_transfer', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_capacity'), 'item', ['capacity'], unique=False)
    op.create_index(op.f('ix_item_in_timestamp'), 'item', ['in_timestamp'], unique=False)
    op.create_index(op.f('ix_item_length'), 'item', ['length'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_index(op.f('ix_item_note'), 'item', ['note'], unique=False)
    op.create_index(op.f('ix_item_out_timestamp'), 'item', ['out_timestamp'], unique=False)
    op.create_index(op.f('ix_item_product_number'), 'item', ['product_number'], unique=False)
    op.create_index(op.f('ix_item_serial_number'), 'item', ['serial_number'], unique=False)
    op.create_index(op.f('ix_item_status'), 'item', ['status'], unique=False)
    op.create_index(op.f('ix_item_type'), 'item', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_type'), table_name='item')
    op.drop_index(op.f('ix_item_status'), table_name='item')
    op.drop_index(op.f('ix_item_serial_number'), table_name='item')
    op.drop_index(op.f('ix_item_product_number'), table_name='item')
    op.drop_index(op.f('ix_item_out_timestamp'), table_name='item')
    op.drop_index(op.f('ix_item_note'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_length'), table_name='item')
    op.drop_index(op.f('ix_item_in_timestamp'), table_name='item')
    op.drop_index(op.f('ix_item_capacity'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_position'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
